### ISSUE TITLE
Data is not anonymised in the fixtures

### ISSUE THREAD

**Issue by pilap82** [viadeo/tetra#13]
Hello,

this is more an FYI than an issue.

I was googling someone to try and find his address... and I've found it in one of your fixtures files (https://github.com/viadeo/tetra/blob/master/test/fixtures/apps/contactslist/response.json).

I guess this is the kind of things (names, emails, positions...) that should be anonymised.
Not sure these people would like to know that some of the information they marked as private (email) in Viadeo is publicly available through GitHub...

P.

**Comment by redking** [comment]
Indeed, that should not have been committed. I've deleted the files in question (which are unused, in any case).

Thanks for the headsup!

**Comment by pilap82** [comment]
my pleasure :)
