### ISSUE TITLE
JQuery library does not load in Opera 12.15 and IE 10 in IFrame which content is loaded from external domain

### ISSUE THREAD

**Issue by titus0039** [viadeo/tetra#23]
Hey, 

Is it possible to migrate to jQuery 1.10.2 ?
This will fix an issue on http://www.viadeo.com/addressbook/import/ iframe where IE and Opera can't load jQuery (1.10.1) when trying to access of the frameElement property.

FYI : BIP-1601 on Atlassian
Please, have a look on http://bugs.jquery.com/ticket/13980

Thanks.

**Comment by thaume** [comment]
@titus0039 I guess it was time to close this issue 😁
