### ISSUE TITLE
bootnode : No define call for comp/comp-autocomplete2 http://requirejs.org/docs/errors.html#nodefine

### ISSUE THREAD

**Issue by nkuoch** [viadeo/tetra#3]
En utilisant data-comp pour du bootnode, ca inclu bien le script, et tout marche bien derrière, mais j'ai cette erreur dans la console:
No define call for comp/comp-autocomplete2 http://requirejs.org/docs/errors.html#nodefine
Mode d'utilisation:
<input type="text" data-comp="comp-autocomplete2" data-event="click" name="skillName" class="js_FieldPush bootnode" size="16" autocomplete="off">

**Comment by redking** [comment]
Fixed
