### ISSUE TITLE
generic_autocomplete

### ISSUE THREAD

**Issue by nkuoch** [viadeo/tetra#5]
2 fixes need to be made in generic_autocomplete.js
1/ replace .html() by .text() when clicking on suggestion and updating the value in the input field : prevent & from becoming &amp; in the field.
2/ remove the encodeURIComponent , coz it seems to "double encode" the string when doing the query.

These changes has been commited on svn, but not through github.

**Comment by redking** [comment]
This is a tetra-ui bug, not tetra! 

https://github.com/viadeo/tetra-ui
