### ISSUE TITLE
tetra_popin : lose static popin context

### ISSUE THREAD

**Issue by duvillierA** [viadeo/tetra#6]
Follow this :
1. Display a static popin with content from the data-target-id
2. Display an external popin with content from the data-target-url
3. Close the visible popin
4. Display the previous static popin

There we are. The context of the static popin is lost.
Indeed, there is no more html content in the element.
Consequently the static popin content is empty.

Please, keep me updated.

Cheers.

**Comment by redking** [comment]
This is a Tetra-UI project bug, and should be raised in that github repo 

https://github.com/viadeo/tetra-ui

**Comment by duvillierA** [comment]
yeah sure...
